@extends('auth.app')

@section('content')
<style>
    .adaptive-card {
        max-width: 480px;
        margin: 0 auto;
        padding: 32px 28px;
        background: #ffffff;
        border-radius: 16px;
        box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.08), 0 8px 10px -6px rgba(0, 0, 0, 0.04);
        border: 1px solid #edf2f7;
    }
    .shield-icon-wrapper {
        width: 60px;
        height: 60px;
        margin: 0 auto 18px;
        border-radius: 50%;
        background: linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%);
        display: flex;
        align-items: center;
        justify-content: center;
        color: #2563eb;
        font-size: 26px;
    }
    .device-banner {
        background: #f8fafc;
        border: 1px solid #e2e8f0;
        border-radius: 10px;
        padding: 12px 14px;
        margin: 18px 0;
        font-size: 13px;
        color: #475569;
        display: flex;
        align-items: flex-start;
        gap: 10px;
    }
    .device-banner .badge-risk {
        background: #e0e7ff;
        color: #3730a3;
        font-weight: 600;
        font-size: 10px;
        padding: 2px 7px;
        border-radius: 4px;
        text-transform: uppercase;
        display: inline-block;
        margin-bottom: 4px;
    }
    .otp-input-group {
        display: flex;
        justify-content: center;
        gap: 8px;
        margin: 20px 0;
    }
    .otp-digit {
        width: 48px;
        height: 56px;
        font-size: 24px;
        font-weight: 700;
        text-align: center;
        border: 2px solid #cbd5e1;
        border-radius: 10px;
        background: #ffffff;
        transition: all 0.2s ease;
        font-family: monospace;
    }
    .otp-digit:focus {
        border-color: #2563eb;
        box-shadow: 0 0 0 4px rgba(37, 99, 235, 0.15);
        outline: none;
    }
    .recovery-mode-box {
        display: none;
        margin: 20px 0;
    }
    .recovery-input {
        letter-spacing: 2px;
        font-family: monospace;
        font-size: 18px;
        text-align: center;
        text-transform: uppercase;
    }
</style>

<div class="adaptive-card">
    <div class="text-center">
        <div class="shield-icon-wrapper">
            <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <rect width="18" height="11" x="3" y="11" rx="2" ry="2"/>
                <path d="M7 11V7a5 5 0 0 1 10 0v4"/>
            </svg>
        </div>
        <h2 class="h4 fw-bold mb-1">Two-Factor Authentication</h2>
        <p class="text-muted small mb-0">
            Enter the 6-digit verification code generated by your Authenticator App (Google / Microsoft Authenticator).
        </p>
    </div>

    @if (!empty($deviceMeta))
    <div class="device-banner">
        <div style="font-size: 20px; line-height: 1;">📱</div>
        <div class="flex-grow-1">
            <span class="badge-risk">Unrecognized Browser</span>
            <div class="fw-semibold text-dark">{{ $deviceMeta['device_name'] ?? 'Web Browser' }}</div>
            <div class="small text-secondary">
                IP: {{ $deviceMeta['ip'] ?? request()->ip() }} &bull; Location: {{ trim(($deviceMeta['city'] ?? '') . ', ' . ($deviceMeta['country'] ?? 'Unknown'), ', ') }}
            </div>
        </div>
    </div>
    @endif

    <p class="text-center small text-secondary my-3">
        Account: <strong>{{ $user->email ?? 'User' }}</strong>
    </p>

    @if (session('success'))
        <div class="alert alert-success py-2 small text-center mb-3">
            {{ session('success') }}
        </div>
    @endif

    @if ($errors->any())
        <div class="alert alert-danger py-2 small mb-3">
            <ul class="mb-0 ps-3">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form method="POST" action="{{ route('adaptive.totp.verify') }}" id="totpForm">
        @csrf
        <input type="hidden" name="code" id="finalCode">

        <!-- Mode A: 6-digit Authenticator interactive pins -->
        <div id="totpBoxSection">
            <div class="otp-input-group" id="otpBoxContainer">
                @for ($i = 0; $i < 6; $i++)
                    <input
                        type="text"
                        inputmode="numeric"
                        pattern="[0-9]*"
                        maxlength="1"
                        class="otp-digit"
                        data-index="{{ $i }}"
                        autocomplete="one-time-code"
                    />
                @endfor
            </div>
            <div class="text-center mb-3">
                <button type="button" class="btn btn-link btn-sm text-decoration-none" id="toggleRecoveryBtn">
                    <i class="fe fe-key me-1"></i>Lost access? Use a backup recovery code
                </button>
            </div>
        </div>

        <!-- Mode B: Single 10-char Recovery Code input -->
        <div id="recoveryBoxSection" class="recovery-mode-box">
            <label class="form-label small fw-semibold text-secondary">Backup Recovery Code</label>
            <input
                type="text"
                id="recoveryInput"
                class="form-control form-control-lg recovery-input"
                placeholder="XXXXX-XXXXX"
                maxlength="12"
                autocomplete="off"
            />
            <div class="d-flex justify-content-between align-items-center mt-2">
                <small class="text-muted">Enter any of your 8-digit emergency recovery codes.</small>
                <button type="button" class="btn btn-link btn-sm text-decoration-none p-0" id="backToTotpBtn">
                    Use 6-digit code
                </button>
            </div>
        </div>

        <!-- Trust / Remember this device checkbox -->
        <div class="form-check mb-3">
            <input class="form-check-input" type="checkbox" name="remember_device" value="1" id="rememberDeviceCheck" checked>
            <label class="form-check-label small text-secondary" for="rememberDeviceCheck">
                Remember this device for 60 days
            </label>
        </div>

        <button type="submit" class="btn btn-primary w-100 py-2 fw-semibold shadow-sm" id="submitBtn">
            Verify & Continue
        </button>
    </form>

    <div class="d-flex justify-content-center align-items-center mt-3 pt-3 border-top">
        <a href="{{ route('login') }}" class="small text-muted text-decoration-none">
            &larr; Back to Login
        </a>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {
    const inputs = document.querySelectorAll('.otp-digit');
    const finalCodeInput = document.getElementById('finalCode');
    const form = document.getElementById('totpForm');
    const submitBtn = document.getElementById('submitBtn');
    const totpBoxSection = document.getElementById('totpBoxSection');
    const recoveryBoxSection = document.getElementById('recoveryBoxSection');
    const toggleRecoveryBtn = document.getElementById('toggleRecoveryBtn');
    const backToTotpBtn = document.getElementById('backToTotpBtn');
    const recoveryInput = document.getElementById('recoveryInput');

    let isRecoveryMode = false;
    let isSubmitting = false;

    // Auto-focus first input
    if (inputs.length > 0) {
        inputs[0].focus();
    }

    // Toggle Recovery Code Mode
    toggleRecoveryBtn.addEventListener('click', function () {
        isRecoveryMode = true;
        totpBoxSection.style.display = 'none';
        recoveryBoxSection.style.display = 'block';
        recoveryInput.focus();
    });

    backToTotpBtn.addEventListener('click', function () {
        isRecoveryMode = false;
        recoveryBoxSection.style.display = 'none';
        totpBoxSection.style.display = 'block';
        inputs[0].focus();
    });

    inputs.forEach((input, index) => {
        // Typing handler
        input.addEventListener('input', function () {
            const val = this.value.replace(/[^0-9]/g, '');
            this.value = val;

            if (val && index < inputs.length - 1) {
                inputs[index + 1].focus();
            }
            updateFinalOtp();
        });

        // Keydown handler
        input.addEventListener('keydown', function (e) {
            if (e.key === 'Backspace' && !this.value && index > 0) {
                inputs[index - 1].focus();
            }
        });

        // Paste handler
        input.addEventListener('paste', function (e) {
            e.preventDefault();
            const pasteData = (e.clipboardData || window.clipboardData).getData('text').replace(/[^0-9]/g, '');
            if (pasteData) {
                const chars = pasteData.slice(0, 6).split('');
                chars.forEach((char, i) => {
                    if (inputs[i]) {
                        inputs[i].value = char;
                    }
                });
                const nextIndex = Math.min(chars.length, inputs.length - 1);
                inputs[nextIndex].focus();
                updateFinalOtp();

                if (chars.length === 6) {
                    triggerSubmit();
                }
            }
        });
    });

    function updateFinalOtp() {
        if (isRecoveryMode) {
            finalCodeInput.value = recoveryInput.value.trim();
        } else {
            let code = '';
            inputs.forEach(input => code += input.value);
            finalCodeInput.value = code;
        }
    }

    function triggerSubmit() {
        if (isSubmitting) return;
        updateFinalOtp();

        if (!isRecoveryMode && finalCodeInput.value.length === 6) {
            isSubmitting = true;
            submitBtn.disabled = true;
            submitBtn.innerHTML = '<span class="spinner-border spinner-border-sm me-2" role="status"></span>Verifying...';
            form.submit();
        }
    }

    form.addEventListener('submit', function (e) {
        updateFinalOtp();

        if (isRecoveryMode) {
            if (finalCodeInput.value.length < 8) {
                e.preventDefault();
                alert('Please enter a valid backup recovery code.');
                return;
            }
        } else {
            if (finalCodeInput.value.length < 6) {
                e.preventDefault();
                alert('Please enter all 6 digits from your Authenticator App.');
                return;
            }
        }

        if (isSubmitting) {
            e.preventDefault();
            return;
        }

        isSubmitting = true;
        submitBtn.disabled = true;
        submitBtn.innerHTML = '<span class="spinner-border spinner-border-sm me-2" role="status"></span>Verifying...';
    });
});
</script>
@endsection
