<?php

namespace App\Modules\Interaction\Traits;

use App\Modules\Interaction\Models\Comment;
use App\Modules\Interaction\Models\Like;
use App\Modules\Interaction\Models\ShareLink;
use Illuminate\Database\Eloquent\Relations\HasMany;

trait CanInteract
{
    /**
     * Get all polymorphic comments authored by this user.
     */
    public function interactionComments(): HasMany
    {
        return $this->hasMany(Comment::class, 'user_id');
    }

    /**
     * Get all polymorphic likes given by this user.
     */
    public function interactionLikes(): HasMany
    {
        return $this->hasMany(Like::class, 'user_id');
    }

    /**
     * Get all share links generated by this user.
     */
    public function shareLinks(): HasMany
    {
        return $this->hasMany(ShareLink::class, 'user_id');
    }

    /**
     * Get all polymorphic bookmarks saved by this user.
     */
    public function bookmarks(): HasMany
    {
        return $this->hasMany(\App\Modules\Interaction\Models\Bookmark::class, 'user_id');
    }
}
